const CONFIG = {
    titleWeb: "From Thành Đạt With Love",
    introTitle: 'Võ Thùy Linh',
    introDesc: `Hay là mình cứ bất chấp hết yêu nhau đi em`,
    btnIntro: '^^Dạ^^',
    title: 'Jocasta có iu Laius không?',
    desc: 'Hãy lựa chọn đúng đắn ',
    btnYes: 'Dạ có',
    btnNo: 'Không bao giờ',
    question: 'Anh biết em sẽ chọn anh mà <3',
    btnReply: 'Gửi cho Laius <3',
    reply: 'Iu Thành Đạt nhiều nhiều',
    mess: 'Anh thương em nhất mà hihi',
    messDesc: 'Chủ nhật anh qua đón nhá',
    btnAccept: 'Oki lun',
    messLink: 'https://https://m.me/cmthanhdat'
